### ISSUE TITLE
Maybe adjustments that may help

### ISSUE THREAD

**Issue by francoism90** [graysky2/auto-reencode#3]
Thanks for creating this script, I'm using it to convert video's to h264. :)
See my gist about some edits I have done:
https://github.com/francoism90/auto-reencode/blob/master/auto-reencode

I would suggest to use `ffprobe` instead of `mediainfo` as it doesn't require any additional install as `ffprobe` should be in most cases included in `ffmpeg`. The hwaccel edits are only useful when using VA-API.

There are however some issues with directories with spaces, don't know why this happens, it could be an issue on my end. I have fixed this by using the following `find` command: `find "${PWD}/"* ..`. Maybe you have a better suggestions?

**Comment by graysky2** [comment]
Looks nice.... any thoughts on syntax to extract the video duration in the "x min y sec" format rather than in the "x sec" format?

**Comment by francoism90** [comment]
@graysky2 Thanks, will check your changes later this week.

I'm using the `ptime` to calculate the bitrate when `ffprobe` is unable to do so, this mainly happens with MKV containers and when tested, the bitrate was almost identical to the video itself. Although I may  look into a better solution like [this](https://trac.ffmpeg.org/wiki/FFprobeTips#Formatcontainerduration) instead.

If using the seconds format, it will be possible to convert this into HH:MM:SS, although I'm not a bash expert, maybe using `date`?

**Comment by graysky2** [comment]
OK... I read through the `ffprobe` man page but didn't see a way to do it natively... an easy fix: https://github.com/graysky2/auto-reencode/commit/1773fad345953fe94859a04bf2d5b891319bad3d
